name = "forbear"
author = "Stefano Zaghi"
copyright  = "Copyright (c) 2017 Stefano Zaghi"
license = "multi-licensing system: GPLv3, BSD2, BSD3, and MIT"
description = "Fortran (progress) B(e)ar envinronment"
homepage = "https://github.com/szaghi/forbear"

[dependencies]
FACE = { git="https://github.com/szaghi/FACE.git" }

[build]
auto-executables = false
auto-examples = false
auto-tests = false

[library]
source-dir = "src/lib"

[install]
library = true

[[test]]
name = "forbear_test"
source-dir = "src/tests"
main = "forbear_test.F90"

[[test]]
name = "forbear_test_elements"
source-dir = "src/tests"
main = "forbear_test_elements.F90"

[[test]]
name = "forbear_test_finish"
source-dir = "src/tests"
main = "forbear_test_finish.F90"

[[test]]
name = "forbear_test_formats"
source-dir = "src/tests"
main = "forbear_test_formats.F90"

[[test]]
name = "forbear_test_frequency"
source-dir = "src/tests"
main = "forbear_test_frequency.F90"

[[test]]
name = "forbear_test_range"
source-dir = "src/tests"
main = "forbear_test_range.F90"

[[test]]
name = "forbear_test_terminal"
source-dir = "src/tests"
main = "forbear_test_terminal.F90"

[[test]]
name = "forbear_test_suspend"
source-dir = "src/tests"
main = "forbear_test_suspend.F90"

[[test]]
name = "forbear_test_template"
source-dir = "src/tests"
main = "forbear_test_template.F90"

[[test]]
name = "forbear_test_zones"
source-dir = "src/tests"
main = "forbear_test_zones.F90"
